# 调试选项
DEBUG_OPTION = True

# 定义字符串常量 (CONST_STRING_*)
CONST_STRING_ELLIPSIS = "..."
CONST_STRING_COLON = ":"
CONST_STRING_LF_NEWLINE = "\n"
CONST_STRING_CRLF_NEWLINE = "\r\n"
CONST_STRING_LEFT_BRACKET = "[ "
CONST_STRING_RIGHT_BRACKET = " ]"

# 定义目录路径常量 (CONST_PATH_*)
CONST_PATH_SYSTEM_INFORMER_SRC = "SystemInformer"
# 工具目录
CONST_PATH_TOOLS_DIRECTORY = "tools"
CONST_PATH_PEVIEW_TOOL_SRC = f"{CONST_PATH_TOOLS_DIRECTORY}/peview"
CONST_PATH_SETUP_TOOL_SRC = f"{CONST_PATH_TOOLS_DIRECTORY}/CustomSetupTool"

# 当开启调试模式时，将只处理 debug_file 变量指定的文件。
DEBUG_FILE = f"{CONST_PATH_SYSTEM_INFORMER_SRC}/version.rc"