data_dict_type = dict[str, str]

debug = True

debug_file = "SystemInformer/SystemInformer.rc"

errno_data = [
    "Button",
    "SysListView32",
    "SysTreeView32",
    "PhTreeNew",
    "MS Shell Dlg",     # Default font name
    "SysLink", 
    "PhColorBox", 
    "PhGraph", 
    "PhHexEdit",
    "Segoe UI",         # Font name
]

data = [
    ("SystemInformer/SystemInformer.rc", "utf-8", {     # File processing...
        "Terminate": "终止",
        "General": "常规",
        "Permissions": "权限",
        "File": "文件",
        "Version:": "版本:",
        "Image file name (Win32):": "映像文件名 (Win32):",
        "Inspect": "检查",
        "Open": "打开",
        "Process": "进程",
        "Command line:": "命令行:",
        "Current directory:": "工作目录:",
        "Started:": "开始于:",
        "Parent console:": "父控制台:",
        "Parent process:": "父进程:",
        "View": "查看",
        "Mitigation policies:": "缓解策略:",
        "Details": "详情",
        "Protection:": "保护:",
        "<a>Company name link</a>": "<a>发行商名称链接</a>",
        "Image type:": "映像类型:",
        "Image file name:": "映像文件名:",
        "Policy": "策略",
        "Modules": "模块",
        "Options": "选项",
        "Threads": "线程",
        "Handles": "句柄",
        "Environment": "环境",
        "Refresh": "刷新",
        "Thread Stack": "线程栈",
        "Copy": "复制",
        "Close": "关闭",
        "About": "关于",
        "Copyright (c) Winsider Seminars && Solutions, Inc.":
            "版权所有 (c) Winsider Seminars && Solutions, Inc.",
        "<a href=\"\"https://systeminformer.sourceforge.io\"\">System Informer on SourceForge.net</a>":
            "<a href=\"\"https://systeminformer.sourceforge.io\"\">SourceForge 上的 System Informer</a>",
        "Diagnostics": "统计信息",
        "OK": "确定",
        "&Start": "启动(&S)",
        "&Pause": "挂起(&S)",
        "Type:": "类型:",
        "Start type:": "启动类型:",
        "Error control:": "错误控制:",
        "Group:": "组:",
        "Binary path:": "映像路径:",
        "Browse...": "选择...",
        "User account:": "用户账户:",
        "Password:": "密码:",
        "Service DLL:": "服务 DLL:",
        "Delayed start": "延迟启动",
        "Information": "信息",
        "Save...": "保存...",
        "Find Handles or DLLs": "查找句柄或 DLL",
        "Find": "查找",
        "Thread Stacks": "线程栈",
        "Users List": "用户列表",
        "Token": "令牌",
        "User:": "用户:",
        "User SID:": "用户 SID:",
        "Session:": "会话:",
        "Unknown": "未知",
        "Elevated:": "提升:",
        "Virtualized:": "虚拟化:",
        "Integrity": "完整性",
        "Advanced": "高级",
        "Default token": "默认令牌",
        "Zombie Processes": "僵尸进程",
        "Processes highlighted red are hidden while those highlighted grey have terminated.":
            "红色高亮的进程已被隐藏，灰色高亮的进程已终止。",
        "&Scan": "扫描",
        "Run As": "以指定用户身份运行",
        "Enter the command to start as the specified user.": "输入命令以指定用户身份运行。",
        "Program:": "程序:",
        "User name:": "用户名:",
        "Toggle elevation": "更改海拔高度",
        "Session ID:": "会话 ID:",
        "Desktop:": "桌面:",
        "Cancel": "取消",
        "Browse": "选择",
        "Create suspended": "创建并挂起",
        "Create UIAccess": "创建 UIAccess",
        "Please wait...": "请稍等...",
        "Progress": "正在进行",
        "Pagefiles": "页面文件",
        "Owner:": "所有者:",
        "Primary group:": "主组:",
        "Virtualization:": "虚拟化:",
        "Linked token": "关联的令牌:",
        "Source": "源",
        "Name:": "名称:",
        "Job": "作业",
        "Processes in job:": "作业中的进程:",
        "Add...": "添加...",
        "Limits:": "限制:",
        "Event": "事件",
        "Signaled:": "有信号:",
        "Set": "设置",
        "Reset": "重置",
        "Pulse": "脉冲",
        "Mutant": "互斥体", 
        "Count:": "计数:", 
        "Abandoned:": "已弃用:", 
        "Semaphore": "信号量", 
        "Current count:": "当前值:", 
        "Maximum count:": "最大值:", 
        "Acquire": "获取", 
        "Release": "释放", 
        "Timer": "计时器", 
        "Statistics": "统计数据", 
        "Active processes": "活动进程数", 
        "Total processes": "进程总数", 
        "Terminated due to job limits": "因作业限制已终止", 
        "Time": "时间", 
        "User time": "用户时间", 
        "Kernel time": "内核时间", 
        "User time (period)": "用户时间 (周期)", 
        "Kernel time (period)": "内核时间 (周期)", 
        "Memory": "内存", 
        "Page faults": "页面错误", 
        "Peak process usage": "进程使用量峰值", 
        "Peak job usage": "作业使用量峰值", 
        "Reads": "读取", 
        "Read bytes": "读取字节", 
        "Writes": "写入", 
        "Write bytes": "写入字节", 
        "Other": "其他", 
        "Other bytes": "其他字节", 
        "Event Pair": "事件配对", 
        "Set low": "设置低值", 
        "Set high": "设置高值", 
        "Affinity": "处理器相关性", 
        "Affinity controls which CPUs threads are allowed to execute on.": "处理器相关性控制线程可以在哪些 CPU 上执行。", 
        "Select all": "全选", 
        "Deselect all": "全不选", 
        "System Information": "系统信息", 
        "Message": "消息", 
        "Title:": "标题:", 
        "Text:": "文字:", 
        "Icon:": "图标:", 
        "Timeout (s):": "超时 (秒):", 
        "Session Properties": "会话属性", 
        "Option": "选项", 
        "Search engine:": "搜索引擎:", 
        "PE viewer:": "PE 查看器:", 
        "Max. size unit:": "最大大小单元:", 
        "Icon processes:": "图标处理:", 
        "Font...": "字体...", 
        "Monospace...": "等宽字体...", 
        "Make default...": "设置默认值...", 
        "Graph history length:": "图像历史长度:", 
        "Automatic": "自动", 
        "Application font:": "应用程序字体:", 
        "System Informer is the default Task Manager:": "System Informer 是默认的任务管理器:", 
        "Symbol path:": "符号路径:", 
        "Highlighting": "高亮显示", 
        "New objects:": "新对象:", 
        "New objects": "新对象", 
        "Removed objects:": "已删除对象:", 
        "Removed objects": "已删除对象", 
        "Highlighting duration:": "高亮显示时长:", 
        "Double-click an item to change it.": "双击项目以更改。", 
        "Enable all": "全部启用", 
        "Disable all": "全部禁用", 
        "Choose Columns": "选择列", 
        "Inactive columns:": "未显示的列:", 
        "Show >": "显示 >", 
        "< Hide": "< 隐藏", 
        "Move up": "上移", 
        "Move down": "下移", 
        "Active columns:": "显示的列:", 
        "Select the columns that will appear in the list.": "选择要在列表中显示的列。", 
        "Network Stack": "网络栈", 
        "Create Service": "创建服务", 
        "Display name:": "显示名称:", 
        "Performance": "性能", 
        "Private bytes": "私有字节", 
        "GDI Handles": "GDI 句柄", 
        "Log": "日志", 
        "Clear": "清空", 
        "Auto-scroll": "自动滚动", 
        "Re-read": "重新读取", 
        "Write": "写入", 
        "Go to...": "转到...", 
        "Memory Protection": "内存保护", 
        "New value:": "新值:", 
        "Strings": "字符串", 
        "Filter": "筛选器", 
        "String Search": "搜索字符串", 
        "Minimum length:": "最小长度:", 
        "Results": "结果", 
        "Results.": "结果", 
        "Detect Unicode": "检测 Unicode", 
        "Search in the following types of memory regions:": "在以下类型的内存区域中进行搜索:", 
        "Private": "私有", 
        "Image": "映像", 
        "Mapped": "映射", 
        "Extended Unicode": "扩展 Unicode", 
        "Graphs": "图像", 
        "Show text": "显示文字", 
        "Use old colors (black background)": "使用旧颜色 (黑色背景)", 
        "Show commit charge instead of physical memory in summary view":
            "在摘要视图中显示提交用量而不是物理内存", 
        "Plugins": "插件", 
        "Changes may require a restart to take effect.": "更改可能需要重启才能生效。", 
        "Disabled plugins (0)": "已禁用插件 (0)", 
        "Handle Statistics": "句柄统计数据", 
        "Handle": "句柄",
        "Process Record": "进程记录", 
        "Parent:": "父进程:", 
        "Terminated:": "结束于:", 
        "Properties": "属性", 
        "Select a Process": "选择进程", 
        "Select a process from the list below.": "从下面的列表中选择一个进程。", 
        "Services": "服务", 
        "Remote Control": "远程控制", 
        "To end the remote control session, press this key and the modifiers selected below:":
            "要结束远程控制会话，请按此键以及下面选择的组合键:", 
        "Capabilities": "兼容性", 
        "Attributes": "属性", 
        "CPU name": "CPU 名称", 
        "Panel layout": "面板布局", 
        "Graph layout": "图像布局", 
        "Utilization:": "使用率:", 
        "Speed:": "速度:", 
        "System": "系统", 
        "Processes": "进程", 
        "Uptime": "运行时间", 
        "&Show one graph per CPU": "每个 CPU 显示一个图表(&S)", 
        "Context switches delta": "上下文切换增量", 
        "Interrupts delta": "中断增量", 
        "DPCs delta": "DPC 增量", 
        "System calls delta": "系统调用增量", 
        "Topology": "拓扑结构", 
        "Cores": "核心", 
        "Sockets": "套接字", 
        "Logical processors": "逻辑处理器", 
        "Latency": "延迟", 
        "Hardware": "硬件", 
        "L1 cache": "L1 缓存", 
        "L2 cache": "L2 缓存", 
        "L3 cache": "L3 缓存",
        "Commit charge": "提交用量",
        "Current": "当前",
        "Peak": "峰值",
        "Limit": "限制",
        "Physical memory": "物理内存",
        "Cache WS": "缓存工作集",
        "Total": "总计",
        "Kernel WS": "内核工作集",
        "Driver WS": "驱动工作集",
        "Paged pool": "分页池",
        "Working set": "工作集",
        "Virtual size": "虚拟内存大小",
        "Allocs delta": "分配增量",
        "Frees delta": "释放增量",
        "Non-paged pool": "非分页池",
        "Usage": "用量",
        "Memory lists": "内存列表",
        "Zeroed": "零化",
        "Modified": "已修改",
        "Free": "空闲",
        "Modified no-write": "已修改不写出",
        "Standby": "待命",
        "Priority 0": "优先级 0",
        "Priority 1": "优先级 1",
        "Priority 2": "优先级 2",
        "Priority 3": "优先级 3",
        "Priority 4": "优先级 4",
        "Priority 5": "优先级 5",
        "Priority 6": "优先级 6",
        "Priority 7": "优先级 7",
        "Paging": "分页",
        "Page faults delta": "页面错误增量",
        "Pagefile writes delta": "页面文件写入增量",
        "Page reads delta": "页面读取增量",
        "Mapped writes delta": "映射写入增量",
        "Modified pagefile": "已修改页面文件",
        "&More": "更多",
        "Reserved": "保留",
        "Mapped IO": "映射 I/O",
        "Mapped reads": "映射读取",
        "Mapped writes": "映射写入",
        "&Empty": "清空",
        "Slots used": "已使用槽",
        "Form factor": "形态因数",
        "Technology": "技术",
        "Memory type": "内存类型",
        "Speed": "速度",
        "Total physical": "物理内存总计",
        "Commit charge:": "提交用量:",
        "Physical memory:": "物理内存:",
        "Read bytes:": "读取字节:",
        "Write bytes:": "写入字节:",
        "Other bytes:": "其他字节:",
        "I/O deltas": "I/O 增量",
        "Reads delta": "读取增量",
        "Read bytes delta": "读取字节增量",
        "Writes delta": "写入增量",
        "Write bytes delta": "写入字节增量",
        "Other delta": "其他增量",
        "Other bytes delta": "其他字节增量",
        "I/O totals": "I/O 总计",
        "Memory Lists": "内存列表",
        "Bad": "损坏",
        "(Repurposed)": "(已重用)",
        "Content layout": "内容布局",
        "Section": "节区",
        "Pin": "固定",
        "Mitigation Policies": "缓解策略",
        "Description:": "描述:",
        "Edit Environment Variable": "编辑环境变量",
        "Value:": "值:",
        "Apply": "应用",
        "Cleanup": "清空",
        "Plugin Properties": "插件属性",
        "Plugin": "插件",
        "Internal name:": "内部名称:",
        "Author:": "作者:",
        "<a>Open</a>": "<a>打开</a>",
        "File name:": "文件名:",
        "Options...": "选项...",
        "Disabled Plugins": "已禁用的插件",
        "Organize Column Sets": "组织列集",
        "Rename": "重命名",
        "Delete": "删除",
        "Run": "运行",
        "&Open:": "打开:",
        "Type the name of a program, folder, document, or Internet resource, and Windows will open it for you.":
            "输入程序、文件夹、文档或互联网资源的名称，Windows 将为您打开它。",
        "&Browse...": "选择...",
        "Create this task with TrustedInstaller privileges.": "以 TrustedInstaller 权限创建此任务",
        "Create this task with Administrative privileges.": "以 Administrators 权限创建此任务",
        "Process dump": "进程转储",
        "Normal": "正常",
        "With data segments": "包含数据段",
        "With full memory": "包含全部内存",
        "With handle data": "包含句柄数据",
        "Filter memory": "筛选内存",
        "Scan memory": "扫描内存",
        "With unloaded modules": "包含未加载模块",
        "With indirectly referenced memory": "包含间接引用内存",
        "Filter module paths": "筛选模块路径",
        "With process and thread data": "包含进程和线程数据",
        "With private read-write memory": "包含私有可读写内存",
        "Without optional data": "排除可选数据",
        "With full memory info": "包含全部内存信息",
        "With thread info": "包含线程数据",
        "With code segments": "包含代码段",
        "Without auxiliary state": "排除次要状态",
        "With full auxiliary state": "包含全部次要状态",
        "With private write-copy memory": "包含私有写时复制内存",
        "Ignore inaccessible memory": "忽略无法访问的内存",
        "With token information": "包含令牌信息",
        "With module headers": "包含模块头部",
        "With filter triage data": "包含筛选分流数据",
        "With AVX state context registers": "包含 AVX 状态上下文寄存器",
        "With Intel processor trace data": "包含 Intel 处理器跟踪数据",
        "Scan inaccessible partial pages": "扫描部分无法访问的页面",
        "Filter write-combined memory": "筛选写合并内存",
        "Save": "保存",
        # line 1497
    }),
    #################################################################################
    ("SystemInformer/mdump.c", "utf-8", {       # File complete.
        "Dump files (*.dmp)": "转储文件 (*.dmp)", 
        "All files (*.*)": "所有文件 (*.*)", 
        "Unable to open the process": "无法打开进程", 
        "Unable to access the dump file": "无法访问转储文件", 
        "Processing module ": "正在处理模块 ", 
        "Processing thread ": "正在处理线程 ", 
        "Processing memory regions": "正在处理内存区域", 
        "Processing kernel minidump": "正在处理内核小型转储文件", 
        "The 32-bit version of System Informer could not be located.":
            "找不到 32 位版本的 System Informer。", 
        "A 64-bit dump will be created instead. Do you want to continue?":
            "将改为创建 64 位转储文件。是否继续？", 
        "Unable to create kernel minidump.": 
            "无法创建内核小型转储文件。", 
        "Kernel minidump of processes require administrative privileges. ": 
            "进程内核小型转储文件需要管理员权限。", 
        "Make sure System Informer is running with administrative privileges.":
            "请确保 System Informer 以管理员权限运行。", 
        "Creating the dump file...": "正在创建转储文件...", 
        "Unable to create the minidump": "无法创建小型转储文件", 
        "Unable to create the minidump.": "无法创建小型转储文件。", 
        "Unknown error.": "未知错误。", 
        "Cancelling...": "正在取消...", 
        "Creating the minidump file...": "正在创建小型转储文件...", 
    }), 
    #################################################################################
] # type: list[tuple[str,         str,         data_dict_type]]
  #                   |            |                 |
  #               file_path     encoding         data_dict