data_dict_type = dict[str, str]

errno_data = [
    "Button",
    "SysListView32",
    "PhTreeNew",
    "MS Shell Dlg",
    "SysLink", 
    "PhColorBox", 
    "PhGraph", 
    "PhHexEdit", 
]

data = [
    ("SystemInformer/SystemInformer.rc", "utf-8", {     # File processing...
        "Terminate": "终止",
        "General": "常规",
        "Permissions": "权限",
        "File": "文件",
        "Version:": "版本:",
        "Image file name (Win32):": "映像文件名（Win32）:",
        "Inspect": "检查",
        "Open": "打开",
        "Process": "进程",
        "Command line:": "命令行:",
        "Current directory:": "工作目录:",
        "Started:": "开始于:",
        "Parent console:": "父控制台:",
        "Parent process:": "父进程:",
        "View": "查看",
        "Mitigation policies:": "缓解策略:",
        "Details": "详情",
        "Protection:": "保护:",
        "<a>Company name link</a>": "<a>发行商名称链接</a>",
        "Image type:": "映像类型:",
        "Image file name:": "映像文件名:",
        "Policy": "策略",
        "Modules": "模块",
        "Options": "选项",
        "Threads": "线程",
        "Handles": "句柄",
        "Environment": "环境",
        "Refresh": "刷新",
        "Thread Stack": "线程栈",
        "Copy": "复制",
        "Close": "关闭",
        "About": "关于",
        "Copyright (c) Winsider Seminars && Solutions, Inc.":
            "版权所有 (c) Winsider Seminars && Solutions, Inc.",
        "<a href=\"\"https://systeminformer.sourceforge.io\"\">System Informer on SourceForge.net</a>":
            "<a href=\"\"https://systeminformer.sourceforge.io\"\">SourceForge 上的 System Informer</a>",
        "Diagnostics": "统计信息",
        "OK": "确定",
        "&Start": "启动(&S)",
        "&Pause": "挂起(&S)",
        "Type:": "类型:",
        "Start type:": "启动类型:",
        "Error control:": "错误控制:",
        "Group:": "组:",
        "Binary path:": "映像路径:",
        "Browse...": "选择...",
        "User account:": "用户账户:",
        "Password:": "密码:",
        "Service DLL:": "服务 DLL:",
        "Delayed start": "延迟启动",
        "Information": "信息",
        "Save...": "保存...",
        "Find Handles or DLLs": "查找句柄或 DLL",
        "Find": "查找",
        "Thread Stacks": "线程栈",
        "Users List": "用户列表",
        "Token": "令牌",
        "User:": "用户:",
        "User SID:": "用户 SID:",
        "Session:": "会话:",
        "Unknown": "未知",
        "Elevated:": "提升:",
        "Virtualized:": "虚拟化:",
        "Integrity": "完整性",
        "Advanced": "高级",
        "Default token": "默认令牌",
        "Zombie Processes": "僵尸进程",
        "Processes highlighted red are hidden while those highlighted grey have terminated.":
            "红色高亮的进程已被隐藏，灰色高亮的进程已终止。",
        "&Scan": "扫描",
        "Run As": "以指定用户身份运行",
        "Enter the command to start as the specified user.": "输入命令以指定用户身份运行。",
        "Program:": "程序:",
        "User name:": "用户名:",
        "Toggle elevation": "更改海拔高度",
        "Session ID:": "会话 ID:",
        "Desktop:": "桌面:",
        "Cancel": "取消",
        "Browse": "选择",
        "Create suspended": "创建并挂起",
        "Create UIAccess": "创建 UIAccess",
        "Please wait...": "请稍等...",
        "Progress": "正在进行",
        "Pagefiles": "页面文件",
        "Owner:": "所有者:",
        "Primary group:": "主组:",
        "Virtualization:": "虚拟化:",
        "Linked token": "关联的令牌:",
        "Source": "源",
        "Name:": "名称:",
        "Job": "作业",
        "Processes in job:": "作业中的进程:",
        "Add...": "添加...",
        "Limits:": "限制:",
        "Event": "事件",
        "Signaled:": "有信号:",
        "Set": "设置",
        "Reset": "重置",
        "Pulse": "脉冲",
        "Mutant": "互斥体", 
        "Count:": "计数:", 
        "Abandoned:": "已弃用:", 
        "Semaphore": "信号量", 
        "Current count:": "当前值:", 
        "Maximum count:": "最大值:", 
        "Acquire": "获取", 
        "Release": "释放", 
        "Timer": "计时器", 
        "Statistics": "统计数据", 
        "Active processes": "活动进程数", 
        "Total processes": "进程总数", 
        "Terminated due to job limits": "因作业限制已终止", 
        "Time": "时间", 
        "User time": "用户时间", 
        "Kernel time": "内核时间", 
        "User time (period)": "用户时间 (周期)", 
        "Kernel time (period)": "内核时间 (周期)", 
        "Memory": "内存", 
        "Page faults": "页面错误", 
        "Peak process usage": "进程使用量峰值", 
        "Peak job usage": "作业使用量峰值", 
        "Reads": "读取", 
        "Read bytes": "读取字节", 
        "Writes": "写入", 
        "Write bytes": "写入字节", 
        "Other": "其他", 
        "Other bytes": "其他字节", 
        "Event Pair": "事件配对", 
        "Set low": "设置低值", 
        "Set high": "设置高值", 
        "Affinity": "处理器相关性", 
        "Affinity controls which CPUs threads are allowed to execute on.": "处理器相关性控制线程可以在哪些 CPU 上执行。", 
        "Select all": "全选", 
        "Deselect all": "全不选", 
        "System Information": "系统信息", 
        "Message": "消息", 
        "Title:": "标题:", 
        "Text:": "文字:", 
        "Icon:": "图标:", 
        "Timeout (s):": "超时 (秒):", 
        "Session Properties": "会话属性", 
        "Option": "选项", 
        "Search engine:": "搜索引擎:", 
        "PE viewer:": "PE 查看器:", 
        "Max. size unit:": "最大大小单元:", 
        "Icon processes:": "图标处理:", 
        "Font...": "字体...", 
        "Monospace...": "等宽字体...", 
        "Make default...": "设置默认值...", 
        "Graph history length:": "图像历史长度:", 
        "Automatic": "自动", 
        "Application font:": "应用程序字体:", 
        "System Informer is the default Task Manager:": "System Informer 是默认的任务管理器:", 
        "Symbol path:": "符号路径:", 
        "Highlighting": "高亮显示", 
        "New objects:": "新对象:", 
        "New objects": "新对象", 
        "Removed objects:": "已删除对象:", 
        "Removed objects": "已删除对象", 
        "Highlighting duration:": "高亮显示时长:", 
        "Double-click an item to change it.": "双击项目以更改。", 
        "Enable all": "全部启用", 
        "Disable all": "全部禁用", 
        "Choose Columns": "选择列", 
        "Inactive columns:": "未显示的列:", 
        "Show >": "显示 >", 
        "< Hide": "< 隐藏", 
        "Move up": "上移", 
        "Move down": "下移", 
        "Active columns:": "显示的列:", 
        "Select the columns that will appear in the list.": "选择要在列表中显示的列。", 
        "Network Stack": "网络栈", 
        "Create Service": "创建服务", 
        "Display name:": "显示名称:", 
        "Performance": "性能", 
        "Private bytes": "私有字节", 
        "GDI Handles": "GDI 句柄", 
        "Log": "日志", 
        "Clear": "清空", 
        "Auto-scroll": "自动滚动", 
        "Re-read": "重新读取", 
        "Write": "写入", 
        "Go to...": "转到...", 
        "Memory Protection": "内存保护", 
        "New value:": "新值:", 
        "Strings": "字符串", 
        "Filter": "筛选器", 
        "String Search": "搜索字符串", 
        "Minimum length:": "最小长度:", 
        "Results": "结果", 
        "Results.": "结果", 
        "Detect Unicode": "检测 Unicode", 
        "Search in the following types of memory regions:": "在以下类型的内存区域中进行搜索:", 
        "Private": "私有", 
        "Image": "映像", 
        "Mapped": "映射", 
        "Extended Unicode": "扩展 Unicode", 
        "Graphs": "图像", 
        "Show text": "显示文字", 
        "Use old colors (black background)": "使用旧颜色 (黑色背景)", 
        "Show commit charge instead of physical memory in summary view":
            "在摘要视图中显示提交用量而不是物理内存", 
        "Plugins": "插件", 
        "Changes may require a restart to take effect.": "更改可能需要重启才能生效。", 
        "Disabled plugins (0)": "已禁用插件 (0)", 
        "Handle Statistics": "句柄统计数据", 
        "Close": "句柄", 
        "Process Record": "进程记录", 
        "Parent:": "父进程:", 
        "Terminated:": "结束于:", 
        "Properties": "属性", 
        "Select a Process": "选择进程", 
        "Select a process from the list below.": "从下面的列表中选择一个进程。", 
        "Services": "服务", 
        "Remote Control": "远程控制", 
        "To end the remote control session, press this key and the modifiers selected below:":
            "要结束远程控制会话，请按此键以及下面选择的组合键:", 
        "Capabilities": "兼容性", 
        "Attributes": "属性", 
        "CPU name": "CPU 名称", 
        "Panel layout": "面板布局", 
        "Graph layout": "图像布局", 
        "Utilization:": "使用率:", 
        "Speed:": "速度:", 
        "System": "系统", 
        "Processes": "进程", 
        "Uptime": "运行时间", 
        "&Show one graph per CPU": "每个 CPU 显示一个图表(&S)", 
        "Context switches delta": "上下文切换增量", 
        "Interrupts delta": "中断增量", 
        "DPCs delta": "DPC 增量", 
        "System calls delta": "系统调用增量", 
        "Topology": "拓扑结构", 
        "Cores": "核心", 
        "Sockets": "套接字", 
        "Logical processors": "逻辑处理器", 
        "Latency": "延迟", 
        "Hardware": "硬件", 
        "L1 cache": "L1 缓存", 
        "L2 cache": "L2 缓存", 
        "L3 cache": "L3 缓存", 
        # line 1093
    }),
    #################################################################################
    ("SystemInformer/mdump.c", "utf-8", {       # File complete.
        "Dump files (*.dmp)": "转储文件 (*.dmp)", 
        "All files (*.*)": "所有文件 (*.*)", 
        "Unable to open the process": "无法打开进程", 
        "Unable to access the dump file": "无法访问转储文件", 
        "Processing module ": "正在处理模块 ", 
        "Processing thread ": "正在处理线程 ", 
        "Processing memory regions": "正在处理内存区域", 
        "Processing kernel minidump": "正在处理内核小型转储文件", 
        "The 32-bit version of System Informer could not be located.":
            "找不到 32 位版本的 System Informer。", 
        "A 64-bit dump will be created instead. Do you want to continue?":
            "将改为创建 64 位转储文件。是否继续？", 
        "Unable to create kernel minidump.": 
            "无法创建内核小型转储文件。", 
        "Kernel minidump of processes require administrative privileges. ": 
            "进程内核小型转储文件需要管理员权限。", 
        "Make sure System Informer is running with administrative privileges.":
            "请确保 System Informer 以管理员权限运行。", 
        "Creating the dump file...": "正在创建转储文件...", 
        "Unable to create the minidump": "无法创建小型转储文件", 
        "Unable to create the minidump.": "无法创建小型转储文件。", 
        "Unknown error.": "未知错误。", 
        "Cancelling...": "正在取消...", 
        "Creating the minidump file...": "正在创建小型转储文件...", 
    }), 
    #################################################################################
] # type: list[tuple[str,         str,         data_dict_type]]
  #                   |            |                 |
  #               file_path     encoding         data_dict