# SHOULD_NOT_TRANSLATE_STRING_LIST 列表包含窗口控件信息、字体信息等不应翻译的内容，
# 即使窗口控件显示的文字或字符串表的其中一项恰好是这些内容，也不应被翻译。
SHOULD_NOT_TRANSLATE_STRING_LIST = [
    "Button",
    "SysListView32",
    "SysTreeView32",
    "PhTreeNew",
    "MS Shell Dlg",     # Default font name
    "SysLink",
    "PhColorBox",
    "PhGraph",
    "PhHexEdit",
    "Segoe UI",         # Font name
    "taskschd.dll",     # {CONST_PATH_SYSTEM_INFORMER_SRC}/admintask.c
    "explorer",
    # -------------------------------------------------------------------
    # Windows Kernel Object Types, from WinObjEx64 -> \ObjectTypes\*
    "ActivationObject",
    "ActivityReference",
    "Adapter",
    "ALPC Port",
    "Callback",
    "Composition",
    "Controller",
    "CoreMessaging",
    "CoverageSampler",
    "DebugObject",
    "Desktop",
    "Device",
    "Directory",
    "DmaAdapter",
    "Driver",
    "DxgkCompositionObject",
    "DxgkCurrentDxgThreadObject",
    "DxgkDisplayManagerObject",
    "DxgkSharedBundleObject",
    "DxgkSharedKeyedMutexObject",
    "DxgkSharedProtectedSessionObject",
    "DxgkSharedResource",
    "DxgkSharedSwapChainObject",
    "DxgkSharedSyncObject",
    "EnergyTracker",
    "EtwConsumer",
    "EtwRegistration",
    "EtwSessionDemuxEntry",
    "Event",
    "File",
    "FilterCommunicationPort",
    "FilterConnectionPort",
    "IoCompletion",
    "IoCompletionReserve",
    "IRTimer",
    "Job",
    "Key",
    "KeyedEvent",
    "Mutant",
    "NdisCmState",
    "Partition",
    "PcwObject",
    "PowerRequest",
    "Process",
    "Profile",
    "PsSiloContextNonPaged",
    "PsSiloContextPaged",
    "RawInputManager",
    "RegistryTransaction",
    "Section",
    "Semaphore",
    "Session",
    "SymbolicLink",
    "Thread",
    "Timer",
    "TmEn",
    "TmRm",
    "TmTm",
    "TmTx",
    "Token",
    "TpWorkerFactory",
    "Type",
    "UserApcReserve",
    "VRegConfigurationContext",
    "WaitCompletionPacket",
    "WindowStation",
    "WmiGuid",
    # Kernel Objects End
]